version: '3.4'
services:

  eupf-ui:
    image: local/eupf/ui:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "http://127.0.0.1:80/healthz"]
    restart: unless-stopped
