version: '3.4'
services:

  eupf-ui:
    image: local/eupf/ui:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "http://127.0.0.1:8081/healthz"]
    restart: unless-stopped
    environment:
      - API_PORT=8080
